# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"GradientDescent": "01_optimizers.ipynb",
         "UpdateBase": "02_updates.ipynb",
         "StandardSPSA": "02_updates.ipynb",
         "ADAGRAD": "02_updates.ipynb",
         "ADAM": "02_updates.ipynb",
         "NADAM": "02_updates.ipynb",
         "AcceptanceBase": "02_updates.ipynb",
         "BlockWithLocalResiduals": "02_updates.ipynb",
         "ModelBase": "03_models.ipynb",
         "Model": "03_models.ipynb",
         "GradientBase": "04_gradient.ipynb",
         "SPSAGradient": "04_gradient.ipynb"}

modules = ["optimizers.py",
           "updates.py",
           "costs.py",
           "gradient.py"]

doc_url = "https://LaptopBiologist.github.io/gradless/"

git_url = "https://github.com/LaptopBiologist/gradless/tree/master/"

def custom_doc_links(name): return None
