# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://LaptopBiologist.github.io/gradless/"

git_url = "https://github.com/LaptopBiologist/gradless/tree/master/"

def custom_doc_links(name): return None
